name: Image Thumbs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  # no cache needed for rustfmt
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  # no cache needed for cargo outdated
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo outdated --exit-code 1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cargo
          shared-key: build
      - run: cargo build --all-features --all-targets --release

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cargo
          shared-key: check
      - run: cargo clippy --all-features --all-targets -- --deny clippy::all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cargo
          shared-key: test
      - run: cargo test --all-features --all-targets